---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config: |
{{ tpl (.Files.Get "files/config.yaml.tpl") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca-crt
data:
  ca.crt: |
{{ .Values.ca.public | indent 4 }}
