---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-client-config
data:
  config: |
{{ tpl (.Files.Get "files/client-config.yaml.tpl") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lighthouse-config
data:
  config: |
{{ tpl (.Files.Get "files/lighthouse-config.yaml.tpl") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca-crt
data:
  ca.crt: |
{{ .Values.ca.public | indent 4 }}
