{{- $root := . -}}
{{- range .Values.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Release.Name }}-{{ .name }}
data:
  node.crt: {{ .public | b64enc }}
  node.key: {{ .private | b64enc }}
{{- end }}
